### ISSUE TITLE
Database.cpp compilation consuming very large amounts of RAM

### ISSUE THREAD

**Issue by judymania** [computernewb/collab-vm-server#118]
I was attempting to compile the master-old branch when the compiler crashed on Database.cpp with an out of memory error. I'm not exactly sure if the code, the database library, or my computer are to blame. The PC I am compiling on has 8 gigabytes of memory and a gigabyte large swap partition. I'll try adding a swap file later and seeing if it fixes the problem.

**Comment by judymania** [comment]
This is a 1.2x issue

**Comment by DESKTOPGOOOSE** [comment]
master-old is not ideal to compile. git clone the release/1.2.11 (with --recursive) and build that. 1.2.10 is not supported and you will not get any help with it.

**Comment by dartzcn** [comment]
You should also use Clang instead of GCC for building 1.2.11. GCC has problems with compiling the database.

**Comment by judymania** [comment]
I'm using master-old because trying to get ODB to work wasted hours of my time. Thanks for the suggestion to use clang.

**Comment by yellows111** [comment]
The bug is that GCC does not fully support one of the language features that sqlite-orm uses (...and knowing how it's going, won't for a long while) as of yet, and so creates an infinite recursion ("consuming very large amounts of RAM") with using an set of near-default optimization values. (anything past -O0)

Fix is to either
1: use LLVM (clang), which supports optimizing the feature
2: for the GCC-hellbent: disable optimization, either globally or just for database components.
