### ISSUE TITLE
This repo is outdated, people.

### ISSUE THREAD

**Issue by duckduckstab1** [computernewb/collab-vm-server#133]
It is recommended to use the newer Collab TS version, as this one memleaks and decided to **nuclear explode.**

**Comment by Undefishin** [comment]
uhh i don't think that's 1.2.11 you're looking at

**Comment by duckduckstab1** [comment]
this is basically 3.0 but whatever you call it

**Comment by modeco80** [comment]
This repository is *not* out of date. The [computernewb/collabvm-1.2.ts](https://github.com/computernewb/collabvm-1.2.ts) repository is a entirely separate project, providing a re-implementation of the collabvm 1.2x server which we essentially use as a hold-over. 

I will most likely be re-initializing the history on the master branch of this repository at some point, or otherwise resetting it.

Closing.
