### ISSUE TITLE
Upgrade Guacamole Version

### ISSUE THREAD

**Issue by dartzcn** [computernewb/collab-vm-server#70]
This will be a big project that requires a lot of undertaking. However, the current version of Guacamole that is built into the server, which I believe is 0.9.5, is extremely old and lacks many new features and performance enhancements found in modern versions of Guacamole. One major milestone for CollabVM 1.3 would be upgrading to a newer version of Guacamole and adding support for some of its new features to the server.

**Comment by modeco80** [comment]
Yeah honestly, I don't mean to be a soul crusher but, the things cosmic did (rewriting bits piecemeal in C++, or completely writing new code in C++ just based off original Guacamole code) basically make this either a herculean effort or just not worth the trouble. 

While it'd be objectively a bit more difficult, I think building a new library for handling display and control would be far more worth it, as Guacamole has it's fair share of issues (including its RDP client allowing RCEs... even though it was fixed, it's still a considerably sized yike), and to be frank, does not do a great job at transport efficiency (since display messages send a base64 encoded image, the data bloat goes from 2-4x the original size, which can add up even with Guacamole's rect optimizations, which also seem to be implemented as a premature optimization to boot. While JPEG helped, it's really just been a band-aid fix which never addressed the root problem of Guacamole itself.).

That, and instead of doing the Cosmic and wrapping around Guacamole in our protocol (which is another thing - I really don't like text protocols where binary can and should be used instead, and I really don't like how Cosmic wrapped around it), we can design our protocol *around* our needs (including making switching to a streaming format later much less painful), making things even faster.

Ideally speaking, to make any display format transitions easier, I personally would make the display either opcodeless or another stream or something (which would require the idea of streams to be a thing, but we can emulate that for a bit until we're actually using webrtc or something of that accord).

**Comment by modeco80** [comment]
Some notes on the new stream framing protocol which will encapsulate all CVM server messages for 1.3.0:

opcodes:
 - connect to stream with id
 - send/recieved message from stream with id
 - disconnect from stream with id
 - ...? (don't really see there being much more)
 
in C++:
```cpp
enum class StreamOpcode : std::uint8_t {
	Connect, // connect (messages will start being sent to this client if the stream ID is valid)

	Message, // a message. can also be sent by client to *send* a message
		 // only to R/W streams though. streams which aren't writable
		 // silently drop the message on the server side.

	Disconnect // disconnect from a stream ID.
		   // (This would be nice to avoid socket over connection - just disconnect from control/display streams or something)
};


// all non-byte integers are network ordered

struct StreamPayloadHeader {
	StreamOpcode opcode;
};

// member trait ebco class
template<StreamOpcode opcode, class Payload>
struct StreamPayload : public StreamPayloadHeader {

	
	// this trait function is exposed by all payload structs
	// 
	constexpr static bool IsA(StreamPayloadHeader& header) {
		return header.opcode == opcode;
	}

	// maybe a constexpr cast helper?
};


struct StreamConnectPayload : public StreamPayload<StreamOpcode::Connect> {
	std::uint8_t streamId;
};

struct StreamMessagePayload : public StreamPayload<StreamOpcode::Message> {
	std::uint8_t streamId;
	std::uint32_t payloadSize;

	// payload data follows
};

struct StreamDisConnectPayload : public StreamPayload<StreamOpcode::Disconnect> {
	std::uint8_t streamId;
};
```

**Comment by modeco80** [comment]
Closing since i effectively turned this into an RFC and well. we're doing it lol
