### ISSUE TITLE
Reimplement HTTP server

### ISSUE THREAD

**Issue by dartzcn** [computernewb/collab-vm-server#71]
Currently being done by MDMCK10, but CollabVM Server 1.3 should have an HTTP server implemented so that admins can easily access the admin panel with no additional configuration or editing any files, as well as having a convenient server to quickly link others to their CVM server instance.

**Comment by modeco80** [comment]
for people who have access to dis15 still there's some nice code for http stuff which makes http messages "generic" (beast uses a different Body template type for strings, a file (which i actually like), and other stuff.)

there's also some boost.json helper code which would allow a schema for objects to be made a LOT easier (although that's for further yak shaving unrelated to this.)

also might block #63 ? idk though

**Comment by modeco80** [comment]
Also, I think another major goal would be - unbelievably - to actually wean off Websocket-- and stop using it. To be honest, websocketmm was written *basically* so I could keep 90% of the collabvm server code still expecting the (imo terrible) lifetime assumptions of websocket++ still working, and not have to touch it too hard. Since we're tackling a lot of core code and possibly rewriting it, I think now is the time to get us off it and switch to a more native approach, or to avoid "one huge class" situations still have a seperate server class BUT be very clear about lifetimes

**Comment by yellows111** [comment]
implemented in #76, <s>but current compilier errors from #75 are blocking it on win64</s> It's fine now, compiles successfully.

**Comment by zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-z** [comment]
Don’t reimplement HTTP server. instead make a separate executable for collabvm.db editor to replace admin panel.

~~or having a hook enabled for admin panel to control vm start, stop, update~~
or have a option to temporarily enable http server for this host session, 
./collab-vm-server 80 http
when http value is supplied the http server is enabled otherwise disabled by default. [or 2nd value]

also there are some unused[unshowed or uneditable by web] value in the database, might as well as add it to the next admin panel update.

**Comment by yellows111** [comment]
`separate executable for editing collabvm.db`
This sounds redundant, since knowing how to use the sqlite3 command line or a GUI editor isn't *that* hard.

As for the parameters currently not implemented into the admin panel, i'm currently considering adding a few more quality of life booleans first, if I can figure out a way to implement them.

**Comment by modeco80** [comment]
Tracking this in a new issue, #100
