### ISSUE TITLE
Add X-Forwarded-For and True-Client-IP support

### ISSUE THREAD

**Issue by dartzcn** [computernewb/collab-vm-server#72]
X-Forwarded-For will allow people to host CVM server through nginx and other proxying services, and True-Client-IP will allow people to host CVM server behind CloudFlare and not risk exposing their IP addresses, while being able to ban people from their VMs.

**Comment by zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-z** [comment]
~~for a easier way, there are 3rd party cloudflare ip header to L4 real-ip plugins, works on almost any software.~~

btw True-Client-IP is a cloudflare enterprise (only) feature… (use CF-Connecting-IP)
<details>
<summary>*Important info if you are proxying with cloudflare* [argo tunneling]</summary>
You’ll need argo tunnel for cloudflare otherwise if you are hosting web on the same ip as vm [or web ip somehow leaked], others can create a domain with cloudflare pointing to your webserver to bypass cloudflare ip lock [cloudflare rules or firewalls].

**Comment by yellows111** [comment]
Other things can use True-Client-IP too, i've found examples of "How to add a True-Client-IP Header to your application" for a couple of cloud services...
About CF-Connecting-IP, Needs to be looked into if this is used on the websocket side of things.

**Comment by modeco80** [comment]
Ideally speaking slotting this into websocketmm should be very easy (try to parse ip address if a range of headers exists, if it fails to parse, close the connection, but if not, initalize some ip address member as that parsed ip)

Proxies should prevent the header being added to anything by users, I know at least that nginx lets you allowlist what IPs it will accept a X-Forwarded-For and such headers (and I believe by default localhost is okayed. I'm not really sure though)

**Comment by zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-z** [comment]
> Ideally speaking slotting this into websocketmm should be very easy

after some reading, websocket does not support headers but every ws is established with 101 header switch. CF-Connecting-IP is send on ws handshake.


Using a [ufw]firewall rule is better than using nginx reverse. Cloudflare have ip list, deny all other ip to ws port.[and turning down ipv6[removing ipv6 interface], ipv6 is a mess.]

Admin actions uses ipdata.GetIP, std print uses ipdata.GetIP. By changing them to ipdata.CFIP. CFIP is stored on first http protocol switch signal. That’s where im stuck on.

[CFIP]
check if CFEnabled=1 otherwise return normal function.
[CFIP]


note: avoid x-forwarded-for, they are unreliable and a pain to mess with.



since cloudflare argo tunnel is paid[free version is useless], i managed to add a secret header

on http switch request, it check for a header called cvmID, if not found or value not match [kill connection]. This way we can eliminate the possibility of bypassing cloudflare by pointing. [ip header set using cloudflare transform rule] [add CFEnabled=1 and CFKey=TEXT NOT NULL to Config]

**Comment by zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-z** [comment]
> Ideally speaking slotting this into websocketmm

i don’t recommend adding them to websocketmm as its related to many guacamole functions, overall it just time wasting to rewrite all these codes. What is really needed is to display real-ip on events like [username changed ip: websocket disconnect ip:] and [admin ban kick copyip] as they all use ipdata.GetIP we can capture the real ip with ws t1 handshake and link it to ip_data.CFIP.

other functions will work normally instead of all these imaginable errors.


banlist can be made using cloudflare list api and firewall rule block by list, with ban command etc. “curl api.cloudflare.com -H “Auth header” -d {[ip,]}”

**Comment by modeco80** [comment]
> after some reading, websocket does not support headers but every ws is established with 101 header switch. CF-Connecting-IP is send on ws handshake.

Your word salad pretty much is the worst thing ever. WebSocket doesn't directly support headers, and I never claimed it did.
X-Forwarded-For is sent along with the initial HTTP 101 request to the server. 

> Using a [ufw]firewall rule is better than using nginx reverse. Cloudflare have ip list, deny all other ip to ws port.

NGINX literally has `deny` and `allow`, just like that (And for more advanced configuration e.g the lister/redirecting to a ban page, the `geo` module provides even more flexibility). And it doesn't tie people down to a shitty backbone created by people who make the choice to still host the likes of KF and co.

Besides, using a port for websockets is something I'm planning to eliminate because the multiple VM ports/cvm servers are just a hack (because collab-vm-server's multiple-vm in one server support pretty much was grafted on and chat is shared.)

> i don’t recommend adding them to websocketmm as its related to many guacamole functions

what? Guacamole only touches websocketmm via the wrapper CollabVMServer provides, websocketmm has nothing to do with Guacamole.

**Comment by yellows111** [comment]
> `multi-node servers were grafted on`

There was an attempt during 1.2.10 but was shafted into an `unstable` branch, in case there were bugs

we was waiting for reports of issues with support in the server after someone told us "it may have issues", then proceeded not to respond on *how* it has issues (do you people actually report bugs correctly? legitimate question)

so it never got merged in to 1.2.11+.

Shame really because looking back on it, the unstable 1.2.10 branch supported multi-node quite well.

**Comment by modeco80** [comment]
Implemented in the internal fork. Shouldn't be too difficult to port it to the public builds

**Comment by zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-z** [comment]
> Implemented in the internal fork. Shouldn't be too difficult to port it to the public builds

does it support header-key or argo tunnel?
> Shouldn't be too difficult to port it to the public builds

no need to port it, just send me the source :D

> Shouldn't be too difficult to port it to the public builds

LOL i need those very badly like really really super pro max X badly…

**Comment by zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-z** [comment]
its been 8 days, why is it so hard to publish a cloudflare supported fork?

**Comment by modeco80** [comment]
Why is it so hard to not be an annoying little shit?

**Comment by zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-z** [comment]
why is it so hard to publish a cloudflare supported fork if you have implemented it in the internal fork?

**Comment by zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-z** [comment]
what even is VM2

**Comment by modeco80** [comment]
Closed by 524bb488bca5931e78e089a8824e6707aa409b81.

By default support is not enabled (because I'm assuming people are stupid and are just gonna forward cvm raw). It can be enabled by editing src/websocketmm/websocket_user.cpp and uncommenting the handy define I have effectively put pointless red arrows on for you.
